export const REQUEST_DELIVERIES = 'REQUEST_DELIVERIES';
export const DELIVERIES_SUCCESS = 'DELIVERIES_SUCCESS';
export const DELIVERIES_ERROR = 'DELIVERIES_ERROR';
export const TOTAL_DELIVERIES = 'TOTAL_DELIVERIES';
